services:
  backend:
    image: timotiusgiovandi/aichart-be
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
  frontend:
    image: timotiusgiovandi/aichart-fe
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_AI_KEY: ${VITE_AI_KEY}
    ports:
      - "80:80"
    depends_on:
      - backend
    